services:
  drinquepedia_web:
    container_name: "drinquepedia_web"
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env.development.local
    command: npm run dev
    ports:
      - "5050:5050"
    volumes:
      - ./web/src:/app/src
      - /app/node_modules/

  drinquepedia_api:
    container_name: "drinquepedia_api"
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - ./api:/app
    depends_on:
      - drinquepedia_db

  drinquepedia_db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "3306:3306"
    volumes:
      - drinquepedia_db:/var/lib/mysql

volumes:
  drinquepedia_db: ~
