/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TudosobrebarIndexRouteImport } from './routes/tudosobrebar/index'
import { Route as DrinquesIndexRouteImport } from './routes/drinques/index'
import { Route as DicasIndexRouteImport } from './routes/dicas/index'
import { Route as DestaquesIndexRouteImport } from './routes/destaques/index'
import { Route as DrinquesTropicaisRouteImport } from './routes/drinques/tropicais'
import { Route as DrinquesMartinisRouteImport } from './routes/drinques/martinis'
import { Route as DrinquesCaipirinhasRouteImport } from './routes/drinques/caipirinhas'
import { Route as DrinquesAaZRouteImport } from './routes/drinques/AaZ'
import { Route as DrinquesDrinkIdRouteImport } from './routes/drinques/$drinkId'
import { Route as DicasInstructionIdRouteImport } from './routes/dicas/$instructionId'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TudosobrebarIndexRoute = TudosobrebarIndexRouteImport.update({
  id: '/tudosobrebar/',
  path: '/tudosobrebar/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesIndexRoute = DrinquesIndexRouteImport.update({
  id: '/drinques/',
  path: '/drinques/',
  getParentRoute: () => rootRouteImport,
} as any)
const DicasIndexRoute = DicasIndexRouteImport.update({
  id: '/dicas/',
  path: '/dicas/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestaquesIndexRoute = DestaquesIndexRouteImport.update({
  id: '/destaques/',
  path: '/destaques/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesTropicaisRoute = DrinquesTropicaisRouteImport.update({
  id: '/drinques/tropicais',
  path: '/drinques/tropicais',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesMartinisRoute = DrinquesMartinisRouteImport.update({
  id: '/drinques/martinis',
  path: '/drinques/martinis',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesCaipirinhasRoute = DrinquesCaipirinhasRouteImport.update({
  id: '/drinques/caipirinhas',
  path: '/drinques/caipirinhas',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesAaZRoute = DrinquesAaZRouteImport.update({
  id: '/drinques/AaZ',
  path: '/drinques/AaZ',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesDrinkIdRoute = DrinquesDrinkIdRouteImport.update({
  id: '/drinques/$drinkId',
  path: '/drinques/$drinkId',
  getParentRoute: () => rootRouteImport,
} as any)
const DicasInstructionIdRoute = DicasInstructionIdRouteImport.update({
  id: '/dicas/$instructionId',
  path: '/dicas/$instructionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dicas/$instructionId': typeof DicasInstructionIdRoute
  '/drinques/$drinkId': typeof DrinquesDrinkIdRoute
  '/drinques/AaZ': typeof DrinquesAaZRoute
  '/drinques/caipirinhas': typeof DrinquesCaipirinhasRoute
  '/drinques/martinis': typeof DrinquesMartinisRoute
  '/drinques/tropicais': typeof DrinquesTropicaisRoute
  '/destaques': typeof DestaquesIndexRoute
  '/dicas': typeof DicasIndexRoute
  '/drinques': typeof DrinquesIndexRoute
  '/tudosobrebar': typeof TudosobrebarIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dicas/$instructionId': typeof DicasInstructionIdRoute
  '/drinques/$drinkId': typeof DrinquesDrinkIdRoute
  '/drinques/AaZ': typeof DrinquesAaZRoute
  '/drinques/caipirinhas': typeof DrinquesCaipirinhasRoute
  '/drinques/martinis': typeof DrinquesMartinisRoute
  '/drinques/tropicais': typeof DrinquesTropicaisRoute
  '/destaques': typeof DestaquesIndexRoute
  '/dicas': typeof DicasIndexRoute
  '/drinques': typeof DrinquesIndexRoute
  '/tudosobrebar': typeof TudosobrebarIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dicas/$instructionId': typeof DicasInstructionIdRoute
  '/drinques/$drinkId': typeof DrinquesDrinkIdRoute
  '/drinques/AaZ': typeof DrinquesAaZRoute
  '/drinques/caipirinhas': typeof DrinquesCaipirinhasRoute
  '/drinques/martinis': typeof DrinquesMartinisRoute
  '/drinques/tropicais': typeof DrinquesTropicaisRoute
  '/destaques/': typeof DestaquesIndexRoute
  '/dicas/': typeof DicasIndexRoute
  '/drinques/': typeof DrinquesIndexRoute
  '/tudosobrebar/': typeof TudosobrebarIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dicas/$instructionId'
    | '/drinques/$drinkId'
    | '/drinques/AaZ'
    | '/drinques/caipirinhas'
    | '/drinques/martinis'
    | '/drinques/tropicais'
    | '/destaques'
    | '/dicas'
    | '/drinques'
    | '/tudosobrebar'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dicas/$instructionId'
    | '/drinques/$drinkId'
    | '/drinques/AaZ'
    | '/drinques/caipirinhas'
    | '/drinques/martinis'
    | '/drinques/tropicais'
    | '/destaques'
    | '/dicas'
    | '/drinques'
    | '/tudosobrebar'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/dicas/$instructionId'
    | '/drinques/$drinkId'
    | '/drinques/AaZ'
    | '/drinques/caipirinhas'
    | '/drinques/martinis'
    | '/drinques/tropicais'
    | '/destaques/'
    | '/dicas/'
    | '/drinques/'
    | '/tudosobrebar/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DicasInstructionIdRoute: typeof DicasInstructionIdRoute
  DrinquesDrinkIdRoute: typeof DrinquesDrinkIdRoute
  DrinquesAaZRoute: typeof DrinquesAaZRoute
  DrinquesCaipirinhasRoute: typeof DrinquesCaipirinhasRoute
  DrinquesMartinisRoute: typeof DrinquesMartinisRoute
  DrinquesTropicaisRoute: typeof DrinquesTropicaisRoute
  DestaquesIndexRoute: typeof DestaquesIndexRoute
  DicasIndexRoute: typeof DicasIndexRoute
  DrinquesIndexRoute: typeof DrinquesIndexRoute
  TudosobrebarIndexRoute: typeof TudosobrebarIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tudosobrebar/': {
      id: '/tudosobrebar/'
      path: '/tudosobrebar'
      fullPath: '/tudosobrebar'
      preLoaderRoute: typeof TudosobrebarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/': {
      id: '/drinques/'
      path: '/drinques'
      fullPath: '/drinques'
      preLoaderRoute: typeof DrinquesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicas/': {
      id: '/dicas/'
      path: '/dicas'
      fullPath: '/dicas'
      preLoaderRoute: typeof DicasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destaques/': {
      id: '/destaques/'
      path: '/destaques'
      fullPath: '/destaques'
      preLoaderRoute: typeof DestaquesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/tropicais': {
      id: '/drinques/tropicais'
      path: '/drinques/tropicais'
      fullPath: '/drinques/tropicais'
      preLoaderRoute: typeof DrinquesTropicaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/martinis': {
      id: '/drinques/martinis'
      path: '/drinques/martinis'
      fullPath: '/drinques/martinis'
      preLoaderRoute: typeof DrinquesMartinisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/caipirinhas': {
      id: '/drinques/caipirinhas'
      path: '/drinques/caipirinhas'
      fullPath: '/drinques/caipirinhas'
      preLoaderRoute: typeof DrinquesCaipirinhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/AaZ': {
      id: '/drinques/AaZ'
      path: '/drinques/AaZ'
      fullPath: '/drinques/AaZ'
      preLoaderRoute: typeof DrinquesAaZRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/$drinkId': {
      id: '/drinques/$drinkId'
      path: '/drinques/$drinkId'
      fullPath: '/drinques/$drinkId'
      preLoaderRoute: typeof DrinquesDrinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicas/$instructionId': {
      id: '/dicas/$instructionId'
      path: '/dicas/$instructionId'
      fullPath: '/dicas/$instructionId'
      preLoaderRoute: typeof DicasInstructionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DicasInstructionIdRoute: DicasInstructionIdRoute,
  DrinquesDrinkIdRoute: DrinquesDrinkIdRoute,
  DrinquesAaZRoute: DrinquesAaZRoute,
  DrinquesCaipirinhasRoute: DrinquesCaipirinhasRoute,
  DrinquesMartinisRoute: DrinquesMartinisRoute,
  DrinquesTropicaisRoute: DrinquesTropicaisRoute,
  DestaquesIndexRoute: DestaquesIndexRoute,
  DicasIndexRoute: DicasIndexRoute,
  DrinquesIndexRoute: DrinquesIndexRoute,
  TudosobrebarIndexRoute: TudosobrebarIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
