/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DicadobarmanRouteImport } from './routes/dicadobarman'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TudosobrebarIndexRouteImport } from './routes/tudosobrebar/index'
import { Route as DrinquesIndexRouteImport } from './routes/drinques/index'
import { Route as DicasIndexRouteImport } from './routes/dicas/index'
import { Route as DestaquesIndexRouteImport } from './routes/destaques/index'
import { Route as TudosobrebarKnowledgeSlugRouteImport } from './routes/tudosobrebar/$knowledgeSlug'
import { Route as DrinquesTropicaisRouteImport } from './routes/drinques/tropicais'
import { Route as DrinquesSmoothiesRouteImport } from './routes/drinques/smoothies'
import { Route as DrinquesShotRouteImport } from './routes/drinques/shot'
import { Route as DrinquesSemalcoolRouteImport } from './routes/drinques/semalcool'
import { Route as DrinquesQuentesRouteImport } from './routes/drinques/quentes'
import { Route as DrinquesMartinisRouteImport } from './routes/drinques/martinis'
import { Route as DrinquesFrozenRouteImport } from './routes/drinques/frozen'
import { Route as DrinquesFestasRouteImport } from './routes/drinques/festas'
import { Route as DrinquesClassicosRouteImport } from './routes/drinques/classicos'
import { Route as DrinquesCaipirinhasRouteImport } from './routes/drinques/caipirinhas'
import { Route as DrinquesAaZRouteImport } from './routes/drinques/AaZ'
import { Route as DrinquesDrinkIdRouteImport } from './routes/drinques/$drinkId'
import { Route as DicasInstructionIdRouteImport } from './routes/dicas/$instructionId'
import { Route as DestaquesHighlightIdRouteImport } from './routes/destaques/$highlightId'
import { Route as DrinquesCaipirinhasSorveteRouteImport } from './routes/drinques/caipirinhas.sorvete'
import { Route as DrinquesCaipirinhasClassicasRouteImport } from './routes/drinques/caipirinhas.classicas'

const DicadobarmanRoute = DicadobarmanRouteImport.update({
  id: '/dicadobarman',
  path: '/dicadobarman',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TudosobrebarIndexRoute = TudosobrebarIndexRouteImport.update({
  id: '/tudosobrebar/',
  path: '/tudosobrebar/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesIndexRoute = DrinquesIndexRouteImport.update({
  id: '/drinques/',
  path: '/drinques/',
  getParentRoute: () => rootRouteImport,
} as any)
const DicasIndexRoute = DicasIndexRouteImport.update({
  id: '/dicas/',
  path: '/dicas/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestaquesIndexRoute = DestaquesIndexRouteImport.update({
  id: '/destaques/',
  path: '/destaques/',
  getParentRoute: () => rootRouteImport,
} as any)
const TudosobrebarKnowledgeSlugRoute =
  TudosobrebarKnowledgeSlugRouteImport.update({
    id: '/tudosobrebar/$knowledgeSlug',
    path: '/tudosobrebar/$knowledgeSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const DrinquesTropicaisRoute = DrinquesTropicaisRouteImport.update({
  id: '/drinques/tropicais',
  path: '/drinques/tropicais',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesSmoothiesRoute = DrinquesSmoothiesRouteImport.update({
  id: '/drinques/smoothies',
  path: '/drinques/smoothies',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesShotRoute = DrinquesShotRouteImport.update({
  id: '/drinques/shot',
  path: '/drinques/shot',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesSemalcoolRoute = DrinquesSemalcoolRouteImport.update({
  id: '/drinques/semalcool',
  path: '/drinques/semalcool',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesQuentesRoute = DrinquesQuentesRouteImport.update({
  id: '/drinques/quentes',
  path: '/drinques/quentes',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesMartinisRoute = DrinquesMartinisRouteImport.update({
  id: '/drinques/martinis',
  path: '/drinques/martinis',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesFrozenRoute = DrinquesFrozenRouteImport.update({
  id: '/drinques/frozen',
  path: '/drinques/frozen',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesFestasRoute = DrinquesFestasRouteImport.update({
  id: '/drinques/festas',
  path: '/drinques/festas',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesClassicosRoute = DrinquesClassicosRouteImport.update({
  id: '/drinques/classicos',
  path: '/drinques/classicos',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesCaipirinhasRoute = DrinquesCaipirinhasRouteImport.update({
  id: '/drinques/caipirinhas',
  path: '/drinques/caipirinhas',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesAaZRoute = DrinquesAaZRouteImport.update({
  id: '/drinques/AaZ',
  path: '/drinques/AaZ',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesDrinkIdRoute = DrinquesDrinkIdRouteImport.update({
  id: '/drinques/$drinkId',
  path: '/drinques/$drinkId',
  getParentRoute: () => rootRouteImport,
} as any)
const DicasInstructionIdRoute = DicasInstructionIdRouteImport.update({
  id: '/dicas/$instructionId',
  path: '/dicas/$instructionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DestaquesHighlightIdRoute = DestaquesHighlightIdRouteImport.update({
  id: '/destaques/$highlightId',
  path: '/destaques/$highlightId',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinquesCaipirinhasSorveteRoute =
  DrinquesCaipirinhasSorveteRouteImport.update({
    id: '/sorvete',
    path: '/sorvete',
    getParentRoute: () => DrinquesCaipirinhasRoute,
  } as any)
const DrinquesCaipirinhasClassicasRoute =
  DrinquesCaipirinhasClassicasRouteImport.update({
    id: '/classicas',
    path: '/classicas',
    getParentRoute: () => DrinquesCaipirinhasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dicadobarman': typeof DicadobarmanRoute
  '/destaques/$highlightId': typeof DestaquesHighlightIdRoute
  '/dicas/$instructionId': typeof DicasInstructionIdRoute
  '/drinques/$drinkId': typeof DrinquesDrinkIdRoute
  '/drinques/AaZ': typeof DrinquesAaZRoute
  '/drinques/caipirinhas': typeof DrinquesCaipirinhasRouteWithChildren
  '/drinques/classicos': typeof DrinquesClassicosRoute
  '/drinques/festas': typeof DrinquesFestasRoute
  '/drinques/frozen': typeof DrinquesFrozenRoute
  '/drinques/martinis': typeof DrinquesMartinisRoute
  '/drinques/quentes': typeof DrinquesQuentesRoute
  '/drinques/semalcool': typeof DrinquesSemalcoolRoute
  '/drinques/shot': typeof DrinquesShotRoute
  '/drinques/smoothies': typeof DrinquesSmoothiesRoute
  '/drinques/tropicais': typeof DrinquesTropicaisRoute
  '/tudosobrebar/$knowledgeSlug': typeof TudosobrebarKnowledgeSlugRoute
  '/destaques': typeof DestaquesIndexRoute
  '/dicas': typeof DicasIndexRoute
  '/drinques': typeof DrinquesIndexRoute
  '/tudosobrebar': typeof TudosobrebarIndexRoute
  '/drinques/caipirinhas/classicas': typeof DrinquesCaipirinhasClassicasRoute
  '/drinques/caipirinhas/sorvete': typeof DrinquesCaipirinhasSorveteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dicadobarman': typeof DicadobarmanRoute
  '/destaques/$highlightId': typeof DestaquesHighlightIdRoute
  '/dicas/$instructionId': typeof DicasInstructionIdRoute
  '/drinques/$drinkId': typeof DrinquesDrinkIdRoute
  '/drinques/AaZ': typeof DrinquesAaZRoute
  '/drinques/caipirinhas': typeof DrinquesCaipirinhasRouteWithChildren
  '/drinques/classicos': typeof DrinquesClassicosRoute
  '/drinques/festas': typeof DrinquesFestasRoute
  '/drinques/frozen': typeof DrinquesFrozenRoute
  '/drinques/martinis': typeof DrinquesMartinisRoute
  '/drinques/quentes': typeof DrinquesQuentesRoute
  '/drinques/semalcool': typeof DrinquesSemalcoolRoute
  '/drinques/shot': typeof DrinquesShotRoute
  '/drinques/smoothies': typeof DrinquesSmoothiesRoute
  '/drinques/tropicais': typeof DrinquesTropicaisRoute
  '/tudosobrebar/$knowledgeSlug': typeof TudosobrebarKnowledgeSlugRoute
  '/destaques': typeof DestaquesIndexRoute
  '/dicas': typeof DicasIndexRoute
  '/drinques': typeof DrinquesIndexRoute
  '/tudosobrebar': typeof TudosobrebarIndexRoute
  '/drinques/caipirinhas/classicas': typeof DrinquesCaipirinhasClassicasRoute
  '/drinques/caipirinhas/sorvete': typeof DrinquesCaipirinhasSorveteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dicadobarman': typeof DicadobarmanRoute
  '/destaques/$highlightId': typeof DestaquesHighlightIdRoute
  '/dicas/$instructionId': typeof DicasInstructionIdRoute
  '/drinques/$drinkId': typeof DrinquesDrinkIdRoute
  '/drinques/AaZ': typeof DrinquesAaZRoute
  '/drinques/caipirinhas': typeof DrinquesCaipirinhasRouteWithChildren
  '/drinques/classicos': typeof DrinquesClassicosRoute
  '/drinques/festas': typeof DrinquesFestasRoute
  '/drinques/frozen': typeof DrinquesFrozenRoute
  '/drinques/martinis': typeof DrinquesMartinisRoute
  '/drinques/quentes': typeof DrinquesQuentesRoute
  '/drinques/semalcool': typeof DrinquesSemalcoolRoute
  '/drinques/shot': typeof DrinquesShotRoute
  '/drinques/smoothies': typeof DrinquesSmoothiesRoute
  '/drinques/tropicais': typeof DrinquesTropicaisRoute
  '/tudosobrebar/$knowledgeSlug': typeof TudosobrebarKnowledgeSlugRoute
  '/destaques/': typeof DestaquesIndexRoute
  '/dicas/': typeof DicasIndexRoute
  '/drinques/': typeof DrinquesIndexRoute
  '/tudosobrebar/': typeof TudosobrebarIndexRoute
  '/drinques/caipirinhas/classicas': typeof DrinquesCaipirinhasClassicasRoute
  '/drinques/caipirinhas/sorvete': typeof DrinquesCaipirinhasSorveteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dicadobarman'
    | '/destaques/$highlightId'
    | '/dicas/$instructionId'
    | '/drinques/$drinkId'
    | '/drinques/AaZ'
    | '/drinques/caipirinhas'
    | '/drinques/classicos'
    | '/drinques/festas'
    | '/drinques/frozen'
    | '/drinques/martinis'
    | '/drinques/quentes'
    | '/drinques/semalcool'
    | '/drinques/shot'
    | '/drinques/smoothies'
    | '/drinques/tropicais'
    | '/tudosobrebar/$knowledgeSlug'
    | '/destaques'
    | '/dicas'
    | '/drinques'
    | '/tudosobrebar'
    | '/drinques/caipirinhas/classicas'
    | '/drinques/caipirinhas/sorvete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dicadobarman'
    | '/destaques/$highlightId'
    | '/dicas/$instructionId'
    | '/drinques/$drinkId'
    | '/drinques/AaZ'
    | '/drinques/caipirinhas'
    | '/drinques/classicos'
    | '/drinques/festas'
    | '/drinques/frozen'
    | '/drinques/martinis'
    | '/drinques/quentes'
    | '/drinques/semalcool'
    | '/drinques/shot'
    | '/drinques/smoothies'
    | '/drinques/tropicais'
    | '/tudosobrebar/$knowledgeSlug'
    | '/destaques'
    | '/dicas'
    | '/drinques'
    | '/tudosobrebar'
    | '/drinques/caipirinhas/classicas'
    | '/drinques/caipirinhas/sorvete'
  id:
    | '__root__'
    | '/'
    | '/dicadobarman'
    | '/destaques/$highlightId'
    | '/dicas/$instructionId'
    | '/drinques/$drinkId'
    | '/drinques/AaZ'
    | '/drinques/caipirinhas'
    | '/drinques/classicos'
    | '/drinques/festas'
    | '/drinques/frozen'
    | '/drinques/martinis'
    | '/drinques/quentes'
    | '/drinques/semalcool'
    | '/drinques/shot'
    | '/drinques/smoothies'
    | '/drinques/tropicais'
    | '/tudosobrebar/$knowledgeSlug'
    | '/destaques/'
    | '/dicas/'
    | '/drinques/'
    | '/tudosobrebar/'
    | '/drinques/caipirinhas/classicas'
    | '/drinques/caipirinhas/sorvete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DicadobarmanRoute: typeof DicadobarmanRoute
  DestaquesHighlightIdRoute: typeof DestaquesHighlightIdRoute
  DicasInstructionIdRoute: typeof DicasInstructionIdRoute
  DrinquesDrinkIdRoute: typeof DrinquesDrinkIdRoute
  DrinquesAaZRoute: typeof DrinquesAaZRoute
  DrinquesCaipirinhasRoute: typeof DrinquesCaipirinhasRouteWithChildren
  DrinquesClassicosRoute: typeof DrinquesClassicosRoute
  DrinquesFestasRoute: typeof DrinquesFestasRoute
  DrinquesFrozenRoute: typeof DrinquesFrozenRoute
  DrinquesMartinisRoute: typeof DrinquesMartinisRoute
  DrinquesQuentesRoute: typeof DrinquesQuentesRoute
  DrinquesSemalcoolRoute: typeof DrinquesSemalcoolRoute
  DrinquesShotRoute: typeof DrinquesShotRoute
  DrinquesSmoothiesRoute: typeof DrinquesSmoothiesRoute
  DrinquesTropicaisRoute: typeof DrinquesTropicaisRoute
  TudosobrebarKnowledgeSlugRoute: typeof TudosobrebarKnowledgeSlugRoute
  DestaquesIndexRoute: typeof DestaquesIndexRoute
  DicasIndexRoute: typeof DicasIndexRoute
  DrinquesIndexRoute: typeof DrinquesIndexRoute
  TudosobrebarIndexRoute: typeof TudosobrebarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dicadobarman': {
      id: '/dicadobarman'
      path: '/dicadobarman'
      fullPath: '/dicadobarman'
      preLoaderRoute: typeof DicadobarmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tudosobrebar/': {
      id: '/tudosobrebar/'
      path: '/tudosobrebar'
      fullPath: '/tudosobrebar'
      preLoaderRoute: typeof TudosobrebarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/': {
      id: '/drinques/'
      path: '/drinques'
      fullPath: '/drinques'
      preLoaderRoute: typeof DrinquesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicas/': {
      id: '/dicas/'
      path: '/dicas'
      fullPath: '/dicas'
      preLoaderRoute: typeof DicasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destaques/': {
      id: '/destaques/'
      path: '/destaques'
      fullPath: '/destaques'
      preLoaderRoute: typeof DestaquesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tudosobrebar/$knowledgeSlug': {
      id: '/tudosobrebar/$knowledgeSlug'
      path: '/tudosobrebar/$knowledgeSlug'
      fullPath: '/tudosobrebar/$knowledgeSlug'
      preLoaderRoute: typeof TudosobrebarKnowledgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/tropicais': {
      id: '/drinques/tropicais'
      path: '/drinques/tropicais'
      fullPath: '/drinques/tropicais'
      preLoaderRoute: typeof DrinquesTropicaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/smoothies': {
      id: '/drinques/smoothies'
      path: '/drinques/smoothies'
      fullPath: '/drinques/smoothies'
      preLoaderRoute: typeof DrinquesSmoothiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/shot': {
      id: '/drinques/shot'
      path: '/drinques/shot'
      fullPath: '/drinques/shot'
      preLoaderRoute: typeof DrinquesShotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/semalcool': {
      id: '/drinques/semalcool'
      path: '/drinques/semalcool'
      fullPath: '/drinques/semalcool'
      preLoaderRoute: typeof DrinquesSemalcoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/quentes': {
      id: '/drinques/quentes'
      path: '/drinques/quentes'
      fullPath: '/drinques/quentes'
      preLoaderRoute: typeof DrinquesQuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/martinis': {
      id: '/drinques/martinis'
      path: '/drinques/martinis'
      fullPath: '/drinques/martinis'
      preLoaderRoute: typeof DrinquesMartinisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/frozen': {
      id: '/drinques/frozen'
      path: '/drinques/frozen'
      fullPath: '/drinques/frozen'
      preLoaderRoute: typeof DrinquesFrozenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/festas': {
      id: '/drinques/festas'
      path: '/drinques/festas'
      fullPath: '/drinques/festas'
      preLoaderRoute: typeof DrinquesFestasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/classicos': {
      id: '/drinques/classicos'
      path: '/drinques/classicos'
      fullPath: '/drinques/classicos'
      preLoaderRoute: typeof DrinquesClassicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/caipirinhas': {
      id: '/drinques/caipirinhas'
      path: '/drinques/caipirinhas'
      fullPath: '/drinques/caipirinhas'
      preLoaderRoute: typeof DrinquesCaipirinhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/AaZ': {
      id: '/drinques/AaZ'
      path: '/drinques/AaZ'
      fullPath: '/drinques/AaZ'
      preLoaderRoute: typeof DrinquesAaZRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/$drinkId': {
      id: '/drinques/$drinkId'
      path: '/drinques/$drinkId'
      fullPath: '/drinques/$drinkId'
      preLoaderRoute: typeof DrinquesDrinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicas/$instructionId': {
      id: '/dicas/$instructionId'
      path: '/dicas/$instructionId'
      fullPath: '/dicas/$instructionId'
      preLoaderRoute: typeof DicasInstructionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destaques/$highlightId': {
      id: '/destaques/$highlightId'
      path: '/destaques/$highlightId'
      fullPath: '/destaques/$highlightId'
      preLoaderRoute: typeof DestaquesHighlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinques/caipirinhas/sorvete': {
      id: '/drinques/caipirinhas/sorvete'
      path: '/sorvete'
      fullPath: '/drinques/caipirinhas/sorvete'
      preLoaderRoute: typeof DrinquesCaipirinhasSorveteRouteImport
      parentRoute: typeof DrinquesCaipirinhasRoute
    }
    '/drinques/caipirinhas/classicas': {
      id: '/drinques/caipirinhas/classicas'
      path: '/classicas'
      fullPath: '/drinques/caipirinhas/classicas'
      preLoaderRoute: typeof DrinquesCaipirinhasClassicasRouteImport
      parentRoute: typeof DrinquesCaipirinhasRoute
    }
  }
}

interface DrinquesCaipirinhasRouteChildren {
  DrinquesCaipirinhasClassicasRoute: typeof DrinquesCaipirinhasClassicasRoute
  DrinquesCaipirinhasSorveteRoute: typeof DrinquesCaipirinhasSorveteRoute
}

const DrinquesCaipirinhasRouteChildren: DrinquesCaipirinhasRouteChildren = {
  DrinquesCaipirinhasClassicasRoute: DrinquesCaipirinhasClassicasRoute,
  DrinquesCaipirinhasSorveteRoute: DrinquesCaipirinhasSorveteRoute,
}

const DrinquesCaipirinhasRouteWithChildren =
  DrinquesCaipirinhasRoute._addFileChildren(DrinquesCaipirinhasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DicadobarmanRoute: DicadobarmanRoute,
  DestaquesHighlightIdRoute: DestaquesHighlightIdRoute,
  DicasInstructionIdRoute: DicasInstructionIdRoute,
  DrinquesDrinkIdRoute: DrinquesDrinkIdRoute,
  DrinquesAaZRoute: DrinquesAaZRoute,
  DrinquesCaipirinhasRoute: DrinquesCaipirinhasRouteWithChildren,
  DrinquesClassicosRoute: DrinquesClassicosRoute,
  DrinquesFestasRoute: DrinquesFestasRoute,
  DrinquesFrozenRoute: DrinquesFrozenRoute,
  DrinquesMartinisRoute: DrinquesMartinisRoute,
  DrinquesQuentesRoute: DrinquesQuentesRoute,
  DrinquesSemalcoolRoute: DrinquesSemalcoolRoute,
  DrinquesShotRoute: DrinquesShotRoute,
  DrinquesSmoothiesRoute: DrinquesSmoothiesRoute,
  DrinquesTropicaisRoute: DrinquesTropicaisRoute,
  TudosobrebarKnowledgeSlugRoute: TudosobrebarKnowledgeSlugRoute,
  DestaquesIndexRoute: DestaquesIndexRoute,
  DicasIndexRoute: DicasIndexRoute,
  DrinquesIndexRoute: DrinquesIndexRoute,
  TudosobrebarIndexRoute: TudosobrebarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
