"""init-tables

Revision ID: 0bc422190d60
Revises: 
Create Date: 2024-03-07 23:10:42.538997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0bc422190d60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('drink',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calories', mysql.SMALLINT(), nullable=True),
    sa.Column('alcoholic_content', sa.String(length=10), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('decoration', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drink_id'), 'drink', ['id'], unique=False)
    op.create_table('ingredient_type',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_type_id'), 'ingredient_type', ['id'], unique=False)
    op.create_table('drink_category',
    sa.Column('drink_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['drink_id'], ['drink.id'], ),
    sa.PrimaryKeyConstraint('drink_id', 'category_id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order', mysql.TINYINT(), nullable=False),
    sa.Column('quantity', mysql.SMALLINT(), nullable=False),
    sa.Column('ingredient_type_id', sa.String(length=36), nullable=True),
    sa.Column('drink_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drink.id'], ),
    sa.ForeignKeyConstraint(['ingredient_type_id'], ['ingredient_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_id'), 'ingredient', ['id'], unique=False)
    op.create_table('preparation_step',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order', mysql.TINYINT(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('drink_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preparation_step_id'), 'preparation_step', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preparation_step_id'), table_name='preparation_step')
    op.drop_table('preparation_step')
    op.drop_index(op.f('ix_ingredient_id'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_table('drink_category')
    op.drop_index(op.f('ix_ingredient_type_id'), table_name='ingredient_type')
    op.drop_table('ingredient_type')
    op.drop_index(op.f('ix_drink_id'), table_name='drink')
    op.drop_table('drink')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
