"""knowledge

Revision ID: 1c9246323170
Revises: 1d0fb1694811
Create Date: 2024-03-19 21:37:52.430234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1c9246323170'
down_revision: Union[str, None] = '1d0fb1694811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('subtitle', sa.String(length=256), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_id'), 'knowledge', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_id'), table_name='knowledge')
    op.drop_table('knowledge')
    # ### end Alembic commands ###
