"""highlights-old-id

Revision ID: 36cd6c5b6633
Revises: 8d60ccfb9ee6
Create Date: 2024-03-13 01:04:49.471012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '36cd6c5b6633'
down_revision: Union[str, None] = '8d60ccfb9ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlight', sa.Column('old_id', mysql.SMALLINT(), nullable=False))
    op.create_index(op.f('ix_highlight_old_id'), 'highlight', ['old_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_highlight_old_id'), table_name='highlight')
    op.drop_column('highlight', 'old_id')
    # ### end Alembic commands ###
