"""remove-instruction-type

Revision ID: 3e50864d8d81
Revises: b04cdf685c7d
Create Date: 2024-03-16 19:21:21.022583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3e50864d8d81'
down_revision: Union[str, None] = 'b04cdf685c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruction', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruction', sa.Column('type', mysql.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
