"""instruction-drink-table

Revision ID: 60801975f385
Revises: 36cd6c5b6633
Create Date: 2024-03-16 18:18:21.732630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60801975f385'
down_revision: Union[str, None] = '36cd6c5b6633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink_instruction',
    sa.Column('drink_id', sa.String(length=36), nullable=False),
    sa.Column('instruction_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drink.id'], ),
    sa.ForeignKeyConstraint(['instruction_id'], ['instruction.id'], ),
    sa.PrimaryKeyConstraint('drink_id', 'instruction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drink_instruction')
    # ### end Alembic commands ###
