"""quantity-as-string

Revision ID: 7008add44a9f
Revises: b9dd1bc719a8
Create Date: 2024-03-10 22:04:40.415695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7008add44a9f'
down_revision: Union[str, None] = 'b9dd1bc719a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'quantity',
               existing_type=mysql.SMALLINT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'quantity',
               existing_type=sa.String(length=50),
               type_=mysql.SMALLINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
