"""add-old-id-to-drinks

Revision ID: 773cdec6d79a
Revises: 0bc422190d60
Create Date: 2024-03-08 01:01:46.237538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '773cdec6d79a'
down_revision: Union[str, None] = '0bc422190d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drink', sa.Column('old_id', mysql.SMALLINT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drink', 'old_id')
    # ### end Alembic commands ###
