"""add-unit-of-measurement-to-ingredient

Revision ID: ad6e07563075
Revises: 773cdec6d79a
Create Date: 2024-03-08 23:42:20.821268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6e07563075'
down_revision: Union[str, None] = '773cdec6d79a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('unit_of_measurement', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'unit_of_measurement')
    # ### end Alembic commands ###
