"""instruction-old-id

Revision ID: b04cdf685c7d
Revises: 60801975f385
Create Date: 2024-03-16 19:20:33.391748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b04cdf685c7d'
down_revision: Union[str, None] = '60801975f385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruction', sa.Column('old_id', mysql.SMALLINT(), nullable=False))
    op.add_column('instruction', sa.Column('type', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_instruction_old_id'), 'instruction', ['old_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruction_old_id'), table_name='instruction')
    op.drop_column('instruction', 'type')
    op.drop_column('instruction', 'old_id')
    # ### end Alembic commands ###
