"""index-for-old-id

Revision ID: b9dd1bc719a8
Revises: f6357cab9223
Create Date: 2024-03-09 16:55:22.398291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9dd1bc719a8'
down_revision: Union[str, None] = 'f6357cab9223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_drink_old_id'), 'drink', ['old_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drink_old_id'), table_name='drink')
    # ### end Alembic commands ###
