"""nullable-fields-on-ingredient

Revision ID: f6357cab9223
Revises: ad6e07563075
Create Date: 2024-03-08 23:45:56.361380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6357cab9223'
down_revision: Union[str, None] = 'ad6e07563075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'quantity',
               existing_type=mysql.SMALLINT(),
               nullable=True)
    op.alter_column('ingredient', 'unit_of_measurement',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'unit_of_measurement',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ingredient', 'quantity',
               existing_type=mysql.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
