name: CI api

on:
  push:
    branches: [master]
    # paths:
    #   - "api/**"
  pull_request:
    branches: [master]
    # paths:
    #   - "api/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.2"
        working-directory: api

      - name: Install Poetry
        run: python3 -m pip install poetry
        working-directory: api

      - name: Install dependencies
        run: poetry install --without doc
        working-directory: api

      - name: MyPy
        run: poetry run task mypy
        working-directory: api

      - name: Tests
        run: poetry run task test
        working-directory: api
