name: CI api

on:
  push:
    branches: [master]
    paths:
      - "api/**"
  pull_request:
    branches: [master]
    # paths:
    #   - "api/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.2"

      - name: Install Poetry
        run: python3 -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Create env file
        run: |
          touch .env
          echo ENV=ci >> .env
          cat .env

      - name: MyPy
        run: poetry run task mypy

      - name: Tests
        run: poetry run task test
